## NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Bracket Indexing and Selection

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting

In [7]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
#Reset array 
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_array = arr[0:6]
slice_of_array[: ] = 100
slice_of_array

array([100, 100, 100, 100, 100, 100])

In [10]:
arr
#slice_of_array 값을 바꿨는데 arr값도 바뀜 .. Broadcasting 
#the changes also occur in our original array! 

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [11]:
#원 배열의 값을 복사해서 쓰면 복사한 배열의 값을 바꾸어도 원배열은 안바뀐다. 
arr_copy = arr.copy()
arr_copy[:]= 99
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [12]:
#확인 
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

## Indexing a 2D array
arr_2d[row][col] 보다는 arr_2d[row,col]과 같은 comma notation 사용 권장

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[1]

array([20, 25, 30])

In [15]:
arr_2d[1,0]

20

In [16]:
arr_2d[1,0]

20

In [17]:
#2D array slicing
#shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

## Fancy Indexing


In [18]:
#set up matrix
arr_2d = np.zeros((10,10))

In [19]:
#Length of array
arr_length = arr_2d.shape[1]

In [20]:
for i in range(arr_length):
    arr_2d[i] = i
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [21]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [22]:
arr_2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
bool_arr = arr > 4

In [26]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
x =2 
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])