## 넘파이 사용하기

In [1]:
import numpy as np

## Numpy Arrays

### 넘파이 어레이 만들기

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Method

### arange
    일정한 간격(입력값으로주어짐)을 가진 값을 출력

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
 (시작값, 끝값, (숫자갯수)) 시작값과 끝값 사이에 같은 간격으로 숫자갯수많큼 출력 

In [12]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

## eye
     단위행렬 생성
  

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

## rand
파라미터로 주어진 형태의 배열에 균일분포랜덤값 할당

In [15]:
np.random.rand(2)

array([0.00276805, 0.25447114])

In [16]:
np.random.rand(3,3)

array([[0.55832923, 0.38913602, 0.68565167],
       [0.95705086, 0.52523267, 0.69936604],
       [0.24680437, 0.8824933 , 0.37606064]])

### randn
 rand 와 같은데 표준분포값을 할당

In [17]:
np.random.randn(2)

array([0.35842144, 0.37526206])

In [18]:
np.random.randn(5,5)

array([[-0.00820747,  0.74113563,  0.61477956,  0.36450612, -0.18415872],
       [ 0.30662364, -1.17415909, -0.32388484, -1.17150875,  0.74545071],
       [-0.78923182,  1.69203494, -0.48530573, -1.20210325, -0.92758755],
       [-0.15623667,  0.22416448,  0.48202528,  0.7422971 , -2.08736599],
       [ 0.28710193,  0.91122596,  0.44113795, -1.01101513,  1.21066213]])

### randint
low(inclusive) high(exclusive) 사이의 값을 리턴 

In [19]:
np.random.randint(1,100)

74

In [20]:
np.random.randint(1,100,10)

array([80, 49, 17, 52, 68,  1, 59, 21, 84, 76])

## 배열의 Attributes 와 Method

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50 ,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([15, 28, 25, 25,  7, 10, 15, 18,  5, 31])

## Reshape
파라미터로 주어진 형태로 변형 
ex) 25개값을 가진 1차원배열 -> (5,5) -> 5행 5열의 2차원배열로

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin
최대 최소값 찾기 or 최댓값, 최솟값의 인덱스찾기

In [25]:
ranarr.max()

31

In [26]:
ranarr.argmax()

9

In [27]:
ranarr.min()

5

In [28]:
ranarr.argmin()

8

## Shape
Shape is attribute that arrays have

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
arr.reshape(1,25).shape

(1, 25)

In [32]:
arr.shape

(25,)

In [33]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [34]:
arr.reshape(25,1).shape

(25, 1)

### dtype

In [35]:
arr.dtype

dtype('int64')